# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7ef0beb4710f9fdbee79627a98d9c8703f6ac29d1195d6cc384f7c952191551050c4ded90a58f3c750f2edc0bd765640cde9818f7b3678f5e8044c99d9a19fa7

test:
  secret_key_base: 06cdc64cee89609953639de49578e7ed95a957be3cb9ba79b7197ef2e0a9ca6156ddeb1a922a6902173c55909bd3cfb82efd25bdf50df9a59b920c00acb5d7a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
